include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  SAST_EXCLUDED_PATHS: "frontend/src/assets/private/**"
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"

export const GH_PAT = "ghp_jrgoU8ts3fbszM5Ln2oH97FGiDX7IU20w4ZN"
